In [16]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv("train.csv")
dft = pd.read_csv("test.csv")

In [18]:
df.head(20)

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy
5,5,qp02zw,48,0:0,0.016262,Residential,2,Not Allowed,Yes,8.446025,Rainy
6,6,qp02zy,48,0:0,0.042247,Residential,3,Allowed,Yes,15.772408,Foggy
7,7,qp08by,48,0:0,0.040135,Residential,1,Not Allowed,No,2.705143,Snowy
8,8,qp08gq,48,0:0,0.001002,Residential,1,Not Allowed,No,18.136899,Foggy
9,9,qp08gy,48,0:0,0.003948,Residential,3,Allowed,Yes,12.738209,Rainy
10,10,qp02zp,48,0:0,0.017780,Residential,1,Not Allowed,No,8.240080,Rainy
11,11,qp02zr,48,0:0,0.089060,Residential,2,Not Allowed,Yes,19.245381,Sunny
12,12,qp02zx,48,0:0,0.050096,Residential,3,Allowed,Yes,8.160115,Rainy
13,13,qp02zz,48,0:0,0.152598,Residential,1,Not Allowed,No,11.509705,Rainy
14,14,qp08br,48,0:0,0.011870,Residential,1,Not Allowed,No,16.336671,Foggy
15,15,qp08bx,48,0:0,0.005091,Residential,1,Not Allowed,No,4.696764,Snowy
16,16,qp08bz,48,0:0,0.001492,Residential,1,Not Allowed,No,19.266717,Sunny
17,17,qp08cp,48,0:0,0.003284,Residential,3,Allowed,Yes,24.318534,Sunny
18,18,qp08fz,48,0:0,0.001297,Residential,2,Not Allowed,Yes,-0.248459,Snowy
19,19,qp08gp,48,0:0,0.003276,Residential,2,Not Allowed,Yes,7.382248,Rainy

In [19]:
df.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [21]:
dft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41778 entries, 0 to 41777
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          41778 non-null  int64
 1   geohash        41778 non-null  object
 2   day            41778 non-null  int64
 3   timestamp      41778 non-null  object
 4   RoadType       41454 non-null  object
 5   NumberofLanes  41778 non-null  int64
 6   LargeVehicles  41778 non-null  object
 7   Landmarks      41778 non-null  object
 8   Temperature    40429 non-null  float64
 9   Weather        41347 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 3.2+ MB

In [22]:
df1 = df["RoadType"].unique()
df2 = dft["geohash"].unique()

In [23]:
df["geohash"].value_counts(ascending=True)

geohash
qp03yn      1
qp09wp      1
qp09fc      1
qp09ch      1
qp09bv      1
         ...
qp09ft    105
qp09uv    105
qp09fq    105
qp09uy    105
qp03zz    105
Name: count, Length: 1249, dtype: int64

In [24]:
df22 = set(df2)
df11 = set(df1)

print(df22 - df11)

{'qp09su', 'qp03w1', 'qp093d', 'qp03rb', 'qp09b4', 'qp095s', 'qp03z2', 'qp0d07', 'qp03wr', 'qp0djq', 'qp0982', 'qp0d1c', 'qp03zg', 'qp08ch', 'qp0991', 'qp0907', 'qp09f8', 'qp09hx', 'qp097h', 'qp09jb', 'qp0dj3', 'qp095f', 'qp0dn1', 'qp09gz', 'qp09gq', 'qp09bm', 'qp03xx', 'qp09vt', 'qp03tx', 'qp06nv', 'qp0946', 'qp03wv', 'qp091s', 'qp09jx', 'qp09gc', 'qp09gr', 'qp097w', 'qp06ps', 'qp096h', 'qp09u2', 'qp09dm', 'qp090b', 'qp093b', 'qp09sy', 'qp0959', 'qp09tp', 'qp096t', 'qp03rr', 'qp099j', 'qp03m7', 'qp03p3', 'qp03nd', 'qp098e', 'qp09vs', 'qp03xj', 'qp09uu', 'qp09jt', 'qp0dhy', 'qp03pm', 'qp09mp', 'qp03yu', 'qp09k5', 'qp09j5', 'qp03wg', 'qp03y8', 'qp09ud', 'qp0d57', 'qp0d0g', 'qp091g', 'qp03r1', 'qp0dh2', 'qp090h', 'qp03mc', 'qp09hq', 'qp03qn', 'qp09f4', 'qp03wk', 'qp094c', 'qp09s2', 'qp09c8', 'qp09uv', 'qp099w', 'qp03yq', 'qp09u3', 'qp09g9', 'qp0dh6', 'qp0d12', 'qp08cm', 'qp09fz', 'qp0dh9', 'qp06nu', 'qp09m0', 'qp03ts', 'qp0d4d', 'qp0d19', 'qp0d5j', 'qp09sj', 'qp096w', 'qp0904', 'qp03yg', 'qp03mw', 'qp0d4g', 'qp096z', 'qp09cj', 'qp094v', 'qp08cp', 'qp096r', 'qp03xc', 'qp08c5', 'qp09sw', 'qp0dj5', 'qp099v', 'qp092q', 'qp09eh', 'qp08bg', 'qp02z5', 'qp0dhv', 'qp03jy', 'qp03qd', 'qp0d1u', 'qp08bh', 'qp03pc', 'qp06pq', 'qp0925', 'qp0d0b', 'qp03zh', 'qp08fw', 'qp091t', 'qp093p', 'qp09c6', 'qp094f', 'qp09hr', 'qp096u', 'qp09gf', 'qp09dx', 'qp0dj7', 'qp09cx', 'qp0dh5', 'qp096c', 'qp094y', 'qp095u', 'qp03zd', 'qp0933', 'qp03q5', 'qp09e8', 'qp0921', 'qp0d5f', 'qp09vy', 'qp09bz', 'qp09gx', 'qp06pt', 'qp03r0', 'qp09be', 'qp09mc', 'qp03p8', 'qp09u9', 'qp03p7', 'qp090c', 'qp090r', 'qp03w4', 'qp03ty', 'qp09fw', 'qp03xd', 'qp095r', 'qp08gr', 'qp06p7', 'qp03qy', 'qp03r2', 'qp09ky', 'qp09bq', 'qp03y7', 'qp09dg', 'qp09ut', 'qp0d01', 'qp098b', 'qp0951', 'qp02zc', 'qp09ew', 'qp09f1', 'qp0d5g', 'qp03t8', 'qp03rc', 'qp03t6', 'qp09hy', 'qp0dje', 'qp06ph', 'qp09jv', 'qp0d1g', 'qp091d', 'qp09st', 'qp02zz', 'qp090w', 'qp03r7', 'qp09sz', 'qp03qr', 'qp09kq', 'qp097s', 'qp09k6', 'qp09ve', 'qp03qb', 'qp09jk', 'qp0922', 'qp03tc', 'qp099s', 'qp093c', 'qp08gv', 'qp0djy', 'qp03jr', 'qp03qj', 'qp099t', 'qp09q5', 'qp03nb', 'qp06pw', 'qp03pe', 'qp097d', 'qp094s', 'qp03z9', 'qp03jw', 'qp03mt', 'qp03t2', 'qp02zq', 'qp0936', 'qp095n', 'qp0d1h', 'qp08fn', 'qp0dh1', 'qp09k4', 'qp09uh', 'qp099m', 'qp03qu', 'qp03r6', 'qp09jp', 'qp09dh', 'qp09fq', 'qp03w6', 'qp0dhu', 'qp03tt', 'qp03xy', 'qp09u4', 'qp0960', 'qp09kd', 'qp09uw', 'qp09w5', 'qp09he', 'qp09gm', 'qp03yy', 'qp096f', 'qp0953', 'qp03wz', 'qp03t9', 'qp03xe', 'qp09bd', 'qp03tm', 'qp0d14', 'qp03v9', 'qp03w7', 'qp099h', 'qp09jn', 'qp09bn', 'qp09mn', 'qp095c', 'qp09s3', 'qp03vc', 'qp03my', 'qp03pu', 'qp08bj', 'qp0d54', 'qp09h0', 'qp09dk', 'qp03tb', 'qp02zp', 'qp09fs', 'qp097c', 'qp02yc', 'qp09ck', 'qp08gq', 'qp09f5', 'qp095d', 'qp02zf', 'qp099y', 'qp03z3', 'qp092m', 'qp093j', 'qp03xk', 'qp03x9', 'qp03tu', 'qp09s8', 'qp09b7', 'qp03yt', 'qp0dh4', 'qp09mz', 'qp0djs', 'qp096y', 'qp099r', 'qp09gb', 'qp09fb', 'qp08gz', 'qp08g7', 'qp09sd', 'qp03wt', 'qp0908', 'qp0d13', 'qp09t4', 'qp02z4', 'qp08bm', 'qp03ps', 'qp09v3', 'qp0d1q', 'qp09d1', 'qp03rs', 'qp03wd', 'qp0943', 'qp097k', 'qp09dt', 'qp03rm', 'qp09mj', 'qp092w', 'qp093w', 'qp09fr', 'qp08b4', 'qp09g1', 'qp09cy', 'qp09hj', 'qp095y', 'qp0909', 'qp03zr', 'qp091r', 'qp091k', 'qp08b6', 'qp02zy', 'qp08fy', 'qp096j', 'qp03mx', 'qp03pv', 'qp09fv', 'qp02zg', 'qp08by', 'qp03rg', 'qp09ku', 'qp09s6', 'qp09yn', 'qp09yp', 'qp02zv', 'qp03ny', 'qp09v6', 'qp091v', 'qp03w3', 'qp0d15', 'qp093z', 'qp03nn', 'qp0973', 'qp09c7', 'qp03r3', 'qp02zh', 'qp03ry', 'qp08fr', 'qp02zd', 'qp092n', 'qp09g2', 'qp09vw', 'qp0d4f', 'qp06pd', 'qp0928', 'qp093m', 'qp03tf', 'qp09y0', 'qp0d49', 'qp09e6', 'qp09g4', 'qp03tw', 'qp0d1m', 'qp093r', 'qp03y4', 'qp0dht', 'qp03zf', 'qp096n', 'qp03wb', 'qp08up', 'qp094e', 'qp09s9', 'qp0d4t', 'qp03zq', 'qp09gv', 'qp094w', 'qp093s', 'qp03q4', 'qp09ev', 'qp096e', 'qp0d04', 'qp09cr', 'qp03yk', 'qp094g', 'qp098j', 'qp09ur', 'qp03qv', 'qp02z3', 'qp03mg', 'qp03q6', 'qp09cv', 'qp03yf', 'qp09uf', 'qp03wp', 'qp09dd', 'qp0938', 'qp0986', 'qp09cn', 'qp091e', 'qp09ft', 'qp095e', 'qp098d', 'qp0d4h', 'qp099p', 'qp08g4', 'qp09e1', 'qp03p0', 'qp0dhb', 'qp09eu', 'qp09m9', 'qp096q', 'qp0dj6', 'qp09th', 'qp0d5c', 'qp0d56', 'qp03wn', 'qp09ge', 'qp09m8', 'qp09ub', 'qp097e', 'qp03qs', 'qp096v', 'qp03x2', 'qp0962', 'qp03r5', 'qp09g6', 'qp09dv', 'qp09uk', 'qp095m', 'qp08gm', 'qp03x1', 'qp0dh0', 'qp03td', 'qp03ze', 'qp0dhh', 'qp091y', 'qp0dhe', 'qp03ws', 'qp03me', 'qp09fd', 'qp08gk', 'qp03mz', 'qp08bd', 'qp098p', 'qp0d05', 'qp097j', 'qp03y1', 'qp09ht', 'qp0d1y', 'qp0dj8', 'qp09fy', 'qp090j', 'qp03m8', 'qp0d5m', 'qp0d0v', 'qp09jz', 'qp090v', 'qp03pp', 'qp03wm', 'qp09sn', 'qp06nt', 'qp0dhm', 'qp0d5h', 'qp094x', 'qp0980', 'qp03re', 'qp0djn', 'qp09gs', 'qp0dhs', 'qp09y5', 'qp091u', 'qp09g3', 'qp09dq', 'qp09k9', 'qp0979', 'qp0d4v', 'qp09kv', 'qp099c', 'qp03x5', 'qp09en', 'qp06nc', 'qp0djb', 'qp09vr', 'qp09eq', 'qp09ue', 'qp09vj', 'qp03rk', 'qp03wu', 'qp06pm', 'qp09e0', 'qp06pj', 'qp09g7', 'qp09gp', 'qp095q', 'qp09fm', 'qp09ey', 'qp06p8', 'qp03v2', 'qp09ej', 'qp0dj1', 'qp0972', 'qp09cg', 'qp0942', 'qp03w8', 'qp09b5', 'qp06p3', 'qp03rx', 'qp03y9', 'qp095v', 'qp097g', 'qp099x', 'qp09ss', 'qp093e', 'qp03q9', 'qp0djd', 'qp09d3', 'qp092t', 'qp0929', 'qp0996', 'qp09gk', 'qp0d53', 'qp093y', 'qp08gw', 'qp03tq', 'qp09m1', 'qp03rt', 'qp03zn', 'qp09cc', 'qp09f3', 'qp08b7', 'qp098k', 'qp03z6', 'qp09h1', 'qp03m2', 'qp08fx', 'qp09gj', 'qp095g', 'qp09fu', 'qp03r8', 'qp09u7', 'qp03zm', 'qp096p', 'qp09e9', 'qp09b1', 'qp03qw', 'qp08bq', 'qp09hs', 'qp09d9', 'qp09em', 'qp090y', 'qp097f', 'qp08gn', 'qp03ym', 'qp03ys', 'qp09ux', 'qp0947', 'qp093t', 'qp03xp', 'qp06p2', 'qp093v', 'qp0998', 'qp03we', 'qp08gt', 'qp0905', 'qp0dh3', 'qp09br', 'qp03tk', 'qp06pk', 'qp09c9', 'qp091n', 'qp09fe', 'qp094j', 'qp08bv', 'qp09f2', 'qp095w', 'qp0981', 'qp0d4q', 'qp08bz', 'qp09cu', 'qp09k3', 'qp03rz', 'qp03pn', 'qp094p', 'qp03zp', 'qp09vk', 'qp0dj0', 'qp03xq', 'qp03z4', 'qp0djj', 'qp09ug', 'qp0968', 'qp098q', 'qp0970', 'qp0901', 'qp03xu', 'qp03mf', 'qp03rw', 'qp09cw', 'qp09f9', 'qp09qn', 'qp03r4', 'qp09gh', 'qp03p6', 'qp0dhk', 'qp090k', 'qp09es', 'qp0djc', 'qp0dhq', 'qp0d1j', 'qp09b0', 'qp02zn', 'qp09hw', 'qp03mu', 'qp03y2', 'qp0d42', 'qp0958', 'qp03zk', 'qp091w', 'qp0dn4', 'qp090d', 'qp03nz', 'qp09e2', 'qp09uy', 'qp02yz', 'qp09tj', 'qp090m', 'qp09jr', 'qp09vq', 'qp0d00', 'qp09u1', 'qp03rj', 'qp03wf', 'qp094t', 'qp03mv', 'qp03q2', 'qp0djf', 'qp09hh', 'qp03rv', 'qp09uc', 'qp03x4', 'qp03qx', 'qp03pk', 'qp03ww', 'qp06pe', 'qp03pt', 'qp095h', 'qp09kz', 'qp08cn', 'qp09m2', 'qp096b', 'qp09ks', 'qp03zz', 'qp09dj', 'qp09tk', 'qp094m', 'qp03q0', 'qp09hv', 'qp09tn', 'qp09up', 'qp09y1', 'qp0902', 'qp09t2', 'qp09tt', 'qp0965', 'qp03mr', 'qp09sr', 'qp094d', 'qp03m9', 'qp0999', 'qp09ex', 'qp06nf', 'qp08bp', 'qp0dj2', 'qp0924', 'qp09mu', 'qp095z', 'qp03qm', 'qp06ne', 'qp09d7', 'qp09kx', 'qp03tv', 'qp08b1', 'qp03nf', 'qp0961', 'qp09v2', 'qp03p2', 'qp096g', 'qp03zy', 'qp03wc', 'qp03nq', 'qp03xz', 'qp09d8', 'qp093u', 'qp095k', 'qp08gj', 'qp099u', 'qp08be', 'qp02zj', 'qp09cd', 'qp0932', 'qp03z8', 'qp03jq', 'qp093g', 'qp09fh', 'qp03nx', 'qp097x', 'qp03w9', 'qp02z7', 'qp09d5', 'qp03w5', 'qp09e7', 'qp0926', 'qp0d4w', 'qp09gw', 'qp097q', 'qp0984', 'qp09gu', 'qp0923', 'qp03te', 'qp095p', 'qp094q', 'qp03xw', 'qp03q8', 'qp09cp', 'qp09et', 'qp02z9', 'qp0d4b', 'qp03yw', 'qp06p9', 'qp09cm', 'qp03qe', 'qp09sx', 'qp0d17', 'qp09f0', 'qp090x', 'qp09g5', 'qp09s7', 'qp08b5', 'qp090e', 'qp09tx', 'qp090t', 'qp0d4s', 'qp06ng', 'qp06p6', 'qp03qp', 'qp02zs', 'qp097m', 'qp09b2', 'qp09yj', 'qp09df', 'qp0987', 'qp09ds', 'qp0954', 'qp09gy', 'qp0956', 'qp09ce', 'qp09f6', 'qp09sq', 'qp0d0t', 'qp03z1', 'qp03ye', 'qp03xf', 'qp0989', 'qp09fj', 'qp0927', 'qp03zs', 'qp094n', 'qp09h5', 'qp09bk', 'qp06p0', 'qp09dw', 'qp0920', 'qp03qg', 'qp09b3', 'qp0d4u', 'qp097z', 'qp099n', 'qp03zt', 'qp099z', 'qp092p', 'qp0dj4', 'qp03x8', 'qp03md', 'qp0900', 'qp03p1', 'qp09e5', 'qp099g', 'qp03rd', 'qp092j', 'qp09sg', 'qp09vx', 'qp09gg', 'qp091m', 'qp09e4', 'qp0d0k', 'qp09du', 'qp09vm', 'qp0903', 'qp09v4', 'qp0d52', 'qp0978', 'qp08bu', 'qp09j7', 'qp03xt', 'qp09uz', 'qp09mb', 'qp0d06', 'qp09qp', 'qp06py', 'qp03pr', 'qp09tq', 'qp09bp', 'qp09jm', 'qp0d1f', 'qp08gx', 'qp0985', 'qp0d59', 'qp09gn', 'qp09bw', 'qp09vu', 'qp0dh7', 'qp08gp', 'qp03zb', 'qp06nb', 'qp09me', 'qp0995', 'qp06n9', 'qp09np', 'qp03pg', 'qp09ms', 'qp03z7', 'qp09u6', 'qp03wj', 'qp096k', 'qp03p4', 'qp091x', 'qp08g6', 'qp09u5', 'qp097v', 'qp09wp', 'qp090n', 'qp03t3', 'qp03wq', 'qp09ek', 'qp06n8', 'qp03pb', 'qp09v1', 'qp03px', 'qp09un', 'qp09k2', 'qp09kw', 'qp09kc', 'qp0944', 'qp092d', 'qp09tr', 'qp08cj', 'qp0d02', 'qp09uq', 'qp09hz', 'qp03yv', 'qp0d50', 'qp03p9', 'qp094u', 'qp08fv', 'qp0d18', 'qp093x', 'qp099b', 'qp0950', 'qp03yb', 'qp03wx', 'qp09vg', 'qp03zw', 'qp03xs', 'qp09t5', 'qp09sc', 'qp0d03', 'qp0d1w', 'qp09vv', 'qp06pg', 'qp03xv', 'qp090p', 'qp0d0y', 'qp0948', 'qp08bx', 'qp09ee', 'qp0dhc', 'qp092r', 'qp0976', 'qp096d', 'qp09ez', 'qp03mb', 'qp0d16', 'qp0dnj', 'qp097y', 'qp09bj', 'qp0945', 'qp0d5b', 'qp0dhg', 'qp03xm', 'qp03vb', 'qp02zm', 'qp09g8', 'qp0d1d', 'qp098c', 'qp09cq', 'qp09vp', 'qp02zu', 'qp093f', 'qp08fh', 'qp06pc', 'qp03tg', 'qp03rn', 'qp03rq', 'qp0djt', 'qp09er', 'qp0djw', 'qp099f', 'qp09kt', 'qp0d58', 'qp03qz', 'qp03qf', 'qp09db', 'qp0d0f', 'qp0d1n', 'qp098r', 'qp0949', 'qp0dhd', 'qp09mr', 'qp08fj', 'qp09bh', 'qp09t9', 'qp03rf', 'qp03z0', 'qp06pu', 'qp03qk', 'qp0dj9', 'qp03nr', 'qp03y3', 'qp09h7', 'qp06nd', 'qp03zc', 'qp09fc', 'qp09e3', 'qp0djm', 'qp094z', 'qp096m', 'qp09ef', 'qp0d48', 'qp09um', 'qp03zv', 'qp09jq', 'qp09v0', 'qp03w0', 'qp09h4', 'qp03wh', 'qp0d4y', 'qp095t', 'qp09hp', 'qp09bx', 'qp09sf', 'qp08bs', 'qp0971', 'qp097t', 'qp09fx', 'qp0941', 'qp09de', 'qp03p5', 'qp03xr', 'qp09k0', 'qp03py', 'qp03pw', 'qp09k8', 'qp09m3', 'qp06p1', 'qp090q', 'qp095j', 'qp092k', 'qp03zj', 'qp0djk', 'qp09mq', 'qp03tz', 'qp098f', 'qp09vh', 'qp08cy', 'qp02z6', 'qp06ny', 'qp092e', 'qp09ct', 'qp03y0', 'qp09tm', 'qp08br', 'qp0974', 'qp09ff', 'qp03qc', 'qp0997', 'qp02zt', 'qp03yx', 'qp097b', 'qp09b6', 'qp09ju', 'qp03mm', 'qp02zk', 'qp0993', 'qp094k', 'qp0975', 'qp09u0', 'qp09mt', 'qp08bn', 'qp09sh', 'qp09kr', 'qp08gy', 'qp0djh', 'qp09d4', 'qp0d0w', 'qp097u', 'qp03ms', 'qp03pz', 'qp09kj', 'qp09hm', 'qp03xb', 'qp09t8', 'qp09cs', 'qp09dc', 'qp09mx', 'qp06p4', 'qp09dn', 'qp03jx', 'qp096s', 'qp03q3', 'qp03m3', 'qp0d0n', 'qp0dhw', 'qp0d0m', 'qp0d4c', 'qp03xn', 'qp09ch', 'qp03rp', 'qp03mk', 'qp0906', 'qp02yf', 'qp02zr', 'qp02z1', 'qp0983', 'qp09dr', 'qp0990', 'qp0d0q', 'qp09hn', 'qp0d55', 'qp02zx', 'qp03np', 'qp08cv', 'qp09cb', 'qp03z5', 'qp03x0', 'qp03wy', 'qp09tv', 'qp099k', 'qp09sk', 'qp08bw', 'qp0994', 'qp06p5', 'qp090s', 'qp092s', 'qp03zu', 'qp094b', 'qp08fz', 'qp09d6', 'qp09vn', 'qp0977', 'qp0930', 'qp09q0', 'qp03pf', 'qp095x', 'qp03w2', 'qp03t7', 'qp02ze', 'qp03r9', 'qp03ru', 'qp06pn', 'qp03yz', 'qp09tw', 'qp03y6', 'qp09fg', 'qp0d1e', 'qp0992', 'qp099q', 'qp09g0', 'qp03xg', 'qp0dhj', 'qp0988', 'qp03x6', 'qp0d1b', 'qp098h', 'qp09cf', 'qp09yh', 'qp098u', 'qp06pv', 'qp0d0c', 'qp09us', 'qp09sv', 'qp09uj', 'qp09ke', 'qp0963', 'qp09kn', 'qp0dh8', 'qp09mw', 'qp0d11', 'qp08bk', 'qp098m', 'qp09fk', 'qp09u8', 'qp092x', 'qp0957', 'qp03pq', 'qp06pb', 'qp09ep', 'qp09gt', 'qp0d5e', 'qp093q', 'qp03jz', 'qp0d1k', 'qp091z', 'qp099d', 'qp09se', 'qp09dp', 'qp094r', 'qp03m6', 'qp03x3', 'qp092h', 'qp091q', 'qp03qt', 'qp098g', 'qp09vd', 'qp09k1', 'qp03q1', 'qp099e', 'qp03mq', 'qp096x', 'qp09bt', 'qp03xh', 'qp09sm', 'qp03qh', 'qp0d10', 'qp03pd', 'qp03yd', 'qp09vz', 'qp0937', 'qp0d4n', 'qp09kf', 'qp03x7', 'qp09f7', 'qp03q7', 'qp0952', 'qp098n', 'qp06pf', 'qp09t0', 'qp09ec', 'qp08ck', 'qp09sp', 'qp08un', 'qp0d0j', 'qp03tr', 'qp03qq', 'qp094h', 'qp09sb', 'qp0d0h', 'qp0d4e', 'qp09je', 'qp0d51', 'qp09eb', 'qp09kb', 'qp03yc', 'qp03nw', 'qp06ns', 'qp095b', 'qp0djg', 'qp0969', 'qp09d2', 'qp09hk', 'qp02zw', 'qp03rh', 'qp09ed'}

In [25]:
df[df["geohash"] == "qp02zt" ]

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
697,697,qp02zt,48,0:15,0.211305,Residential,1,Not Allowed,No,-0.794609,Snowy
1413,1413,qp02zt,48,0:30,0.161412,Residential,2,Not Allowed,Yes,12.212404,Rainy
2161,2161,qp02zt,48,0:45,0.183307,Residential,3,Allowed,Yes,24.116755,Sunny
2924,2924,qp02zt,48,1:0,0.142723,Residential,1,Not Allowed,No,24.640264,Sunny
...,...,...,...,...,...,...,...,...,...,...,...
72867,72867,qp02zt,49,1:0,0.202691,Residential,2,Not Allowed,Yes,10.672073,Rainy
73730,73730,qp02zt,49,1:15,0.103521,Residential,2,Not Allowed,Yes,17.029867,Foggy
74615,74615,qp02zt,49,1:30,0.152495,Residential,1,Not Allowed,No,22.853673,Sunny
75514,75514,qp02zt,49,1:45,0.141422,Residential,3,Allowed,Yes,20.423213,Sunny
76406,76406,qp02zt,49,2:0,0.035086,Residential,1,Not Allowed,No,16.333061,Foggy